"""initial schema

Revision ID: 0c2e168a6d1c
Revises:
Create Date: 2026-01-05 22:34:45.748357

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c2e168a6d1c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("encrypted_password", sa.Text(), nullable=True),
        sa.Column("email_confirmed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("invited_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("confirmation_token", sa.Text(), nullable=True),
        sa.Column("confirmation_sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("recovery_token", sa.Text(), nullable=True),
        sa.Column("recovery_sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("email_change_token_new", sa.Text(), nullable=True),
        sa.Column("email_change", sa.Text(), nullable=True),
        sa.Column("email_change_sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_sign_in_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("raw_app_meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_user_meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_super_admin", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("phone_confirmed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("phone_change", sa.Text(), nullable=True),
        sa.Column("phone_change_token", sa.Text(), nullable=True),
        sa.Column("phone_change_sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("email_change_token_current", sa.Text(), nullable=True),
        sa.Column("email_change_confirm_status", sa.Integer(), nullable=True),
        sa.Column("banned_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("reauthentication_token", sa.Text(), nullable=True),
        sa.Column("reauthentication_sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_sso_user", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(op.f("ix_auth_users_email"), "users", ["email"], unique=True, schema="auth")
    op.create_table(
        "companies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("company_reg_no", sa.Text(), nullable=False),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column("contact_first_name", sa.Text(), nullable=True),
        sa.Column("contact_last_name", sa.Text(), nullable=True),
        sa.Column("contact_telephone", sa.Text(), nullable=True),
        sa.Column("contact_user_id", sa.UUID(), nullable=True),
        sa.Column("registered_since", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_chat_bubble_colour", sa.Text(), nullable=True),
        sa.Column("bot_chat_bubble_colour", sa.Text(), nullable=True),
        sa.Column("send_button_and_box", sa.Text(), nullable=True),
        sa.Column("user_chat_font_colour", sa.Text(), nullable=True),
        sa.Column("bot_chat_font_colour", sa.Text(), nullable=True),
        sa.Column("font", sa.Text(), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("bot_profile_picture", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_companies_company_reg_no"), "companies", ["company_reg_no"], unique=True
    )
    op.create_index(
        op.f("ix_companies_contact_email"), "companies", ["contact_email"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("telephone", sa.Text(), nullable=True),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("company_reg_no", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("field_of_expertise", sa.Text(), nullable=True),
        sa.Column("years_of_experience", sa.BigInteger(), nullable=True),
        sa.Column("user_access", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("is_validator", sa.Boolean(), nullable=True),
        sa.Column("CV_text", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profiles_company_reg_no"), "profiles", ["company_reg_no"], unique=False
    )
    op.create_index(op.f("ix_profiles_email"), "profiles", ["email"], unique=False)
    op.create_index(op.f("ix_profiles_username"), "profiles", ["username"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "chatmessages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatmessages_user_id"), "chatmessages", ["user_id"], unique=False)
    op.create_table(
        "chatmessagescollector",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chatmessagescollector_user_id"), "chatmessagescollector", ["user_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column(
            "severity_levels",
            sa.Enum("PUBLIC", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="security_level"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING",
                "ON_REVIEW",
                "REJECTED",
                "VALIDATED_STORED",
                "VALIDATED_AWAITING",
                name="status_enum",
            ),
            nullable=True,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("reviewer", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_index(op.f("ix_documents_reviewer"), "documents", ["reviewer"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED", "STARTED", "IN_PROGRESS", "COMPLETED", name="session_status_enum"
            ),
            nullable=True,
        ),
        sa.Column("password_changed", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("company_reg_no", sa.Text(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id", "company_reg_no"),
    )
    op.create_index(
        op.f("ix_user_roles_company_reg_no"), "user_roles", ["company_reg_no"], unique=False
    )
    op.create_table(
        "document_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("assigned_by", sa.UUID(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", name="document_status"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    op.drop_table("document_assignments")
    op.drop_index(op.f("ix_user_roles_company_reg_no"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_documents_reviewer"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_chatmessagescollector_user_id"), table_name="chatmessagescollector")
    op.drop_table("chatmessagescollector")
    op.drop_index(op.f("ix_chatmessages_user_id"), table_name="chatmessages")
    op.drop_table("chatmessages")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_profiles_username"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_email"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_company_reg_no"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_companies_contact_email"), table_name="companies")
    op.drop_index(op.f("ix_companies_company_reg_no"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_auth_users_email"), table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
