"""create all remaining tables

Revision ID: 0fff0536d5d5
Revises: 8fb698c314e7
Create Date: 2026-01-04 02:16:38.432164

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fff0536d5d5"
down_revision: Union[str, Sequence[str], None] = "8fb698c314e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('email', sa.Text(), nullable=False),
    # sa.Column('encrypted_password', sa.Text(), nullable=True),
    # sa.Column('email_confirmed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('invited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('confirmation_token', sa.Text(), nullable=True),
    # sa.Column('confirmation_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('recovery_token', sa.Text(), nullable=True),
    # sa.Column('recovery_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('email_change_token_new', sa.Text(), nullable=True),
    # sa.Column('email_change', sa.Text(), nullable=True),
    # sa.Column('email_change_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('last_sign_in_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('raw_app_meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # sa.Column('raw_user_meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('phone', sa.Text(), nullable=True),
    # sa.Column('phone_confirmed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('phone_change', sa.Text(), nullable=True),
    # sa.Column('phone_change_token', sa.Text(), nullable=True),
    # sa.Column('phone_change_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('confirmed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('email_change_token_current', sa.Text(), nullable=True),
    # sa.Column('email_change_confirm_status', sa.Integer(), nullable=True),
    # sa.Column('banned_until', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('reauthentication_token', sa.Text(), nullable=True),
    # sa.Column('reauthentication_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('is_sso_user', sa.Boolean(), nullable=True),
    # sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # schema='auth'
    # )
    # op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_table(
        "companies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("company_reg_no", sa.Text(), nullable=False),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column("contact_first_name", sa.Text(), nullable=True),
        sa.Column("contact_last_name", sa.Text(), nullable=True),
        sa.Column("contact_telephone", sa.Text(), nullable=True),
        sa.Column("contact_user_id", sa.UUID(), nullable=True),
        sa.Column("registered_since", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_chat_bubble_colour", sa.Text(), nullable=True),
        sa.Column("bot_chat_bubble_colour", sa.Text(), nullable=True),
        sa.Column("send_button_and_box", sa.Text(), nullable=True),
        sa.Column("user_chat_font_colour", sa.Text(), nullable=True),
        sa.Column("bot_chat_font_colour", sa.Text(), nullable=True),
        sa.Column("font", sa.Text(), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("bot_profile_picture", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_companies_company_reg_no"), "companies", ["company_reg_no"], unique=True
    )
    op.create_index(
        op.f("ix_companies_contact_email"), "companies", ["contact_email"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("telephone", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column(
            "department",
            sa.Enum(
                "AI_CC",
                "PLANNING",
                "ANALYTICS",
                "HR",
                "DATA_CLOUD",
                "SALES",
                "MARKETING",
                name="department",
            ),
            nullable=True,
        ),
        sa.Column("field_of_expertise", sa.Text(), nullable=True),
        sa.Column("years_of_experience", sa.Text(), nullable=True),
        sa.Column("cv_text", sa.Text(), nullable=True),
        sa.Column("is_validator", sa.Boolean(), nullable=True),
        sa.Column(
            "user_access",
            sa.Enum("ADMIN", "MANAGER", "EMPLOYEE", "GUEST", name="user_access_levels"),
            nullable=True,
        ),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column("company_reg_no", sa.Text(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("char_length(username) >= 3", name="username_length"),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(["id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_profiles_company_id"), "profiles", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_profiles_company_reg_no"), "profiles", ["company_reg_no"], unique=False
    )
    op.create_index(op.f("ix_profiles_email"), "profiles", ["email"], unique=False)
    op.create_table(
        "chat_messages_collector",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_collector_user_id"),
        "chat_messages_collector",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages_helper",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_helper_user_id"), "chat_messages_helper", ["user_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column(
            "severity_levels",
            sa.Enum("PUBLIC", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="security_level"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING",
                "ON_REVIEW",
                "REJECTED",
                "VALIDATED_STORED",
                "VALIDATED_AWAITING",
                name="status_enum",
            ),
            nullable=True,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("reviewer", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_index(op.f("ix_documents_reviewer"), "documents", ["reviewer"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED", "STARTED", "IN_PROGRESS", "COMPLETED", name="session_status_enum"
            ),
            nullable=True,
        ),
        sa.Column("password_changed", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("company_reg_no", sa.Text(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id", "company_reg_no"),
    )
    op.create_index(
        op.f("ix_user_roles_company_reg_no"), "user_roles", ["company_reg_no"], unique=False
    )
    op.create_table(
        "document_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("assigned_by", sa.UUID(), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", name="document_status"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    op.drop_table("document_assignments")
    op.drop_index(op.f("ix_user_roles_company_reg_no"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_documents_reviewer"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_chat_messages_helper_user_id"), table_name="chat_messages_helper")
    op.drop_table("chat_messages_helper")
    op.drop_index(op.f("ix_chat_messages_collector_user_id"), table_name="chat_messages_collector")
    op.drop_table("chat_messages_collector")
    op.drop_index(op.f("ix_profiles_email"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_company_reg_no"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_company_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_companies_contact_email"), table_name="companies")
    op.drop_index(op.f("ix_companies_company_reg_no"), table_name="companies")
    op.drop_table("companies")
    # REMOVED - don't drop auth.users (managed separately)
    # op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    # op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
