"""updated sessions and questions again 3

Revision ID: 20dea5eb9afb
Revises: b576626af99f
Create Date: 2026-01-11 20:44:51.952548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '20dea5eb9afb'
down_revision: Union[str, Sequence[str], None] = 'b576626af99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessagescollector', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('chatmessagescollector', sa.Column('messages', sa.Text(), nullable=True))
    op.create_index(op.f('ix_chatmessagescollector_session_id'), 'chatmessagescollector', ['session_id'], unique=False)
    op.create_foreign_key(None, 'chatmessagescollector', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chatmessagescollector', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessagescollector', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chatmessagescollector', type_='foreignkey')
    op.drop_index(op.f('ix_chatmessagescollector_session_id'), table_name='chatmessagescollector')
    op.drop_column('chatmessagescollector', 'messages')
    op.drop_column('chatmessagescollector', 'session_id')
    # ### end Alembic commands ###
