"""Add knowledghe base stuff

Revision ID: 398f5837f248
Revises: e039944678ca
Create Date: 2026-01-25 19:12:00.446894

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '398f5837f248'
down_revision: str | Sequence[str] | None = 'e039944678ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('company_reg_no', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_access', 'knowledge_bases', ['access_level'], unique=False)
    op.create_index('idx_kb_active', 'knowledge_bases', ['is_active'], unique=False)
    op.create_index('idx_kb_company', 'knowledge_bases', ['company_id', 'company_reg_no'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_company_id'), 'knowledge_bases', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_company_reg_no'), 'knowledge_bases', ['company_reg_no'], unique=False)
    op.create_table('kb_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('company_reg_no', sa.String(length=50), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_doc_access', 'kb_documents', ['access_level'], unique=False)
    op.create_index('idx_kb_doc_company', 'kb_documents', ['company_id', 'company_reg_no'], unique=False)
    op.create_index('idx_kb_doc_kb', 'kb_documents', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_documents_access_level'), 'kb_documents', ['access_level'], unique=False)
    op.create_index(op.f('ix_kb_documents_company_id'), 'kb_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_kb_documents_company_reg_no'), 'kb_documents', ['company_reg_no'], unique=False)
    op.create_index(op.f('ix_kb_documents_kb_id'), 'kb_documents', ['kb_id'], unique=False)
    op.create_table('kb_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('company_reg_no', sa.String(length=50), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['kb_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_chunk_access', 'kb_chunks', ['access_level'], unique=False)
    op.create_index('idx_kb_chunk_company', 'kb_chunks', ['company_id', 'company_reg_no'], unique=False)
    op.create_index('idx_kb_chunk_doc', 'kb_chunks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_kb_chunks_access_level'), 'kb_chunks', ['access_level'], unique=False)
    op.create_index(op.f('ix_kb_chunks_company_id'), 'kb_chunks', ['company_id'], unique=False)
    op.create_index(op.f('ix_kb_chunks_company_reg_no'), 'kb_chunks', ['company_reg_no'], unique=False)
    op.create_index(op.f('ix_kb_chunks_doc_id'), 'kb_chunks', ['doc_id'], unique=False)
    # Drop old tables - must drop child (kbchunks) before parent (kbdocuments) due to FK constraint
    op.drop_index(op.f('idx_kbchunks_embedding_ivfflat'), table_name='kbchunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_kbchunks_tsv'), table_name='kbchunks', postgresql_using='gin')
    op.drop_index(op.f('ix_kbchunks_accesslevel'), table_name='kbchunks')
    op.drop_index(op.f('ix_kbchunks_doc_id'), table_name='kbchunks')
    op.drop_table('kbchunks')
    op.drop_index(op.f('ix_kbdocuments_accesslevel'), table_name='kbdocuments')
    op.drop_index(op.f('ix_kbdocuments_companyid'), table_name='kbdocuments')
    op.drop_index(op.f('ix_kbdocuments_companyregno'), table_name='kbdocuments')
    op.drop_table('kbdocuments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kbchunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doc_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sourcefile', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('accesslevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['kbdocuments.id'], name=op.f('kbchunks_doc_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('kbchunks_pkey'))
    )
    op.create_index(op.f('ix_kbchunks_doc_id'), 'kbchunks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_kbchunks_accesslevel'), 'kbchunks', ['accesslevel'], unique=False)
    op.create_index(op.f('idx_kbchunks_tsv'), 'kbchunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_kbchunks_embedding_ivfflat'), 'kbchunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('kbdocuments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('sourcefile', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('accesslevel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('companyid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('companyregno', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doctype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('lastmodifieddate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kbdocuments_pkey'))
    )
    op.create_index(op.f('ix_kbdocuments_companyregno'), 'kbdocuments', ['companyregno'], unique=False)
    op.create_index(op.f('ix_kbdocuments_companyid'), 'kbdocuments', ['companyid'], unique=False)
    op.create_index(op.f('ix_kbdocuments_accesslevel'), 'kbdocuments', ['accesslevel'], unique=False)
    op.drop_index(op.f('ix_kb_chunks_doc_id'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_company_reg_no'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_company_id'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_access_level'), table_name='kb_chunks')
    op.drop_index('idx_kb_chunk_doc', table_name='kb_chunks')
    op.drop_index('idx_kb_chunk_company', table_name='kb_chunks')
    op.drop_index('idx_kb_chunk_access', table_name='kb_chunks')
    op.drop_table('kb_chunks')
    op.drop_index(op.f('ix_kb_documents_kb_id'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_company_reg_no'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_company_id'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_access_level'), table_name='kb_documents')
    op.drop_index('idx_kb_doc_kb', table_name='kb_documents')
    op.drop_index('idx_kb_doc_company', table_name='kb_documents')
    op.drop_index('idx_kb_doc_access', table_name='kb_documents')
    op.drop_table('kb_documents')
    op.drop_index(op.f('ix_knowledge_bases_company_reg_no'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_company_id'), table_name='knowledge_bases')
    op.drop_index('idx_kb_company', table_name='knowledge_bases')
    op.drop_index('idx_kb_active', table_name='knowledge_bases')
    op.drop_index('idx_kb_access', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
