"""updated document with author and company id

Revision ID: 4a079dbfcb67
Revises: b905a850c6f2
Create Date: 2026-01-11 20:06:34.654332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4a079dbfcb67'
down_revision: Union[str, Sequence[str], None] = 'b905a850c6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('author_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('company_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_documents_author_id'), 'documents', ['author_id'], unique=False)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'profiles', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_author_id'), table_name='documents')
    op.drop_column('documents', 'company_id')
    op.drop_column('documents', 'author_id')
    # ### end Alembic commands ###
