"""added validator

Revision ID: 56f08f7ee28f
Revises: e5fd4fb1f2f8
Create Date: 2026-01-12 00:02:12.454995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '56f08f7ee28f'
down_revision: Union[str, Sequence[str], None] = 'e5fd4fb1f2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('responsible', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_responsible'), 'documents', ['responsible'], unique=False)
    op.create_foreign_key(None, 'documents', 'profiles', ['responsible'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_responsible'), table_name='documents')
    op.drop_column('documents', 'responsible')
    # ### end Alembic commands ###
