"""create projects table

Revision ID: 5a03a1ace78d
Revises: 32ee2324d901
Create Date: 2026-01-08 05:54:30.390037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a03a1ace78d'
down_revision: Union[str, Sequence[str], None] = '32ee2324d901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_reg_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='projects_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['profiles.id'], name='projects_manager_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_manager_id', 'projects', ['manager_id'], unique=False)
    op.create_index('idx_projects_company_id', 'projects', ['company_id'], unique=False)
    op.create_index('idx_projects_company_reg_no', 'projects', ['company_reg_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_projects_company_reg_no', table_name='projects')
    op.drop_index('idx_projects_company_id', table_name='projects')
    op.drop_index('idx_projects_manager_id', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###

