"""updated sessions and questions

Revision ID: 64e9188c73f7
Revises: 5a03a1ace78d
Create Date: 2026-01-08 17:21:53.531067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64e9188c73f7'
down_revision: Union[str, Sequence[str], None] = '5a03a1ace78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_projects_company_id'), table_name='projects')
    op.drop_index(op.f('idx_projects_company_reg_no'), table_name='projects')
    op.drop_index(op.f('idx_projects_manager_id'), table_name='projects')
    op.drop_index(op.f('idx_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.add_column('questions', sa.Column('questions', postgresql.ARRAY(sa.Text()), nullable=False))
    op.add_column('questions', sa.Column('status', postgresql.ARRAY(sa.Text()), nullable=False))
    op.add_column('questions', sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('questions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=True)
    op.drop_constraint(op.f('questions_session_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.drop_column('questions', 'question_text')
    op.add_column('sessions', sa.Column('doc_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('chat_messages_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('topic', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'sessions', 'documents', ['doc_id'], ['doc_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'topic')
    op.drop_column('sessions', 'chat_messages_id')
    op.drop_column('sessions', 'doc_id')
    op.add_column('questions', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_session_id_fkey'), 'questions', 'sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.alter_column('questions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'topics')
    op.drop_column('questions', 'status')
    op.drop_column('questions', 'questions')
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_reg_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('projects_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['profiles.id'], name=op.f('projects_manager_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('idx_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('idx_projects_manager_id'), 'projects', ['manager_id'], unique=False)
    op.create_index(op.f('idx_projects_company_reg_no'), 'projects', ['company_reg_no'], unique=False)
    op.create_index(op.f('idx_projects_company_id'), 'projects', ['company_id'], unique=False)
    # ### end Alembic commands ###
