"""add kb_documents table for RAG

Revision ID: e039944678ca
Revises: 56f08f7ee28f
Create Date: 2026-01-16 00:01:01.634293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e039944678ca'
down_revision: Union[str, Sequence[str], None] = '56f08f7ee28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kbdocuments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('sourcefile', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('accesslevel', sa.Integer(), nullable=True),
    sa.Column('companyid', sa.Integer(), nullable=True),
    sa.Column('companyregno', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('doctype', sa.String(length=50), nullable=True),
    sa.Column('createdat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastmodifieddate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kbdocuments_accesslevel'), 'kbdocuments', ['accesslevel'], unique=False)
    op.create_index(op.f('ix_kbdocuments_companyid'), 'kbdocuments', ['companyid'], unique=False)
    op.create_index(op.f('ix_kbdocuments_companyregno'), 'kbdocuments', ['companyregno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kbdocuments_companyregno'), table_name='kbdocuments')
    op.drop_index(op.f('ix_kbdocuments_companyid'), table_name='kbdocuments')
    op.drop_index(op.f('ix_kbdocuments_accesslevel'), table_name='kbdocuments')
    op.drop_table('kbdocuments')
    # ### end Alembic commands ###
