"""change chatmessagescollector messages to jsonb

Revision ID: e5fd4fb1f2f8
Revises: a270b72a64df
Create Date: 2026-01-11 20:58:22.368590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5fd4fb1f2f8'
down_revision: Union[str, Sequence[str], None] = 'a270b72a64df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatmessagescollector', 'messages',
           existing_type=sa.TEXT(),
           type_=postgresql.JSONB(astext_type=sa.Text()),
           nullable=False,
           postgresql_using='messages::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatmessagescollector', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
