/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type {EditorThemeClasses} from 'lexical';

export const PlaygroundEditorTheme: EditorThemeClasses = {
    autocomplete: 'TCEditorTheme__autocomplete',
    blockCursor: 'TCEditorTheme__blockCursor',
    characterLimit: 'TCEditorTheme__characterLimit',
    code: 'TCEditorTheme__code',
    codeHighlight: {
        atrule: 'TCEditorTheme__tokenAttr',
        attr: 'TCEditorTheme__tokenAttr',
        boolean: 'TCEditorTheme__tokenProperty',
        builtin: 'TCEditorTheme__tokenSelector',
        cdata: 'TCEditorTheme__tokenComment',
        char: 'TCEditorTheme__tokenSelector',
        class: 'TCEditorTheme__tokenFunction',
        'class-name': 'TCEditorTheme__tokenFunction',
        comment: 'TCEditorTheme__tokenComment',
        constant: 'TCEditorTheme__tokenProperty',
        deleted: 'TCEditorTheme__tokenProperty',
        doctype: 'TCEditorTheme__tokenComment',
        entity: 'TCEditorTheme__tokenOperator',
        function: 'TCEditorTheme__tokenFunction',
        important: 'TCEditorTheme__tokenVariable',
        inserted: 'TCEditorTheme__tokenSelector',
        keyword: 'TCEditorTheme__tokenAttr',
        namespace: 'TCEditorTheme__tokenVariable',
        number: 'TCEditorTheme__tokenProperty',
        operator: 'TCEditorTheme__tokenOperator',
        prolog: 'TCEditorTheme__tokenComment',
        property: 'TCEditorTheme__tokenProperty',
        punctuation: 'TCEditorTheme__tokenPunctuation',
        regex: 'TCEditorTheme__tokenVariable',
        selector: 'TCEditorTheme__tokenSelector',
        string: 'TCEditorTheme__tokenSelector',
        symbol: 'TCEditorTheme__tokenProperty',
        tag: 'TCEditorTheme__tokenProperty',
        url: 'TCEditorTheme__tokenOperator',
        variable: 'TCEditorTheme__tokenVariable',
    },
    embedBlock: {
        base: 'TCEditorTheme__embedBlock',
        focus: 'TCEditorTheme__embedBlockFocus',
    },
    hashtag: 'TCEditorTheme__hashtag',
    heading: {
        h1: 'TCEditorTheme__h1',
        h2: 'TCEditorTheme__h2',
        h3: 'TCEditorTheme__h3',
        h4: 'TCEditorTheme__h4',
        h5: 'TCEditorTheme__h5',
        h6: 'TCEditorTheme__h6',
    },
    hr: 'TCEditorTheme__hr',
    image: 'editor-image',
    indent: 'TCEditorTheme__indent',
    inlineImage: 'inline-editor-image',
    layoutContainer: 'TCEditorTheme__layoutContainer',
    layoutItem: 'TCEditorTheme__layoutItem',
    link: 'TCEditorTheme__link',
    list: {
        checklist: 'TCEditorTheme__checklist',
        listitem: 'TCEditorTheme__listItem',
        listitemChecked: 'TCEditorTheme__listItemChecked',
        listitemUnchecked: 'TCEditorTheme__listItemUnchecked',
        nested: {
            listitem: 'TCEditorTheme__nestedListItem',
        },
        olDepth: [
            'TCEditorTheme__ol1',
            'TCEditorTheme__ol2',
            'TCEditorTheme__ol3',
            'TCEditorTheme__ol4',
            'TCEditorTheme__ol5',
        ],
        ul: 'TCEditorTheme__ul',
    },
    ltr: 'TCEditorTheme__ltr',
    mark: 'TCEditorTheme__mark',
    markOverlap: 'TCEditorTheme__markOverlap',
    paragraph: 'TCEditorTheme__paragraph',
    quote: 'TCEditorTheme__quote',
    rtl: 'TCEditorTheme__rtl',
    table: 'TCEditorTheme__table',
    tableAddColumns: 'TCEditorTheme__tableAddColumns',
    tableAddRows: 'TCEditorTheme__tableAddRows',
    tableCell: 'TCEditorTheme__tableCell',
    tableCellActionButton: 'TCEditorTheme__tableCellActionButton',
    tableCellActionButtonContainer:
        'TCEditorTheme__tableCellActionButtonContainer',
    tableCellEditing: 'TCEditorTheme__tableCellEditing',
    tableCellHeader: 'TCEditorTheme__tableCellHeader',
    tableCellPrimarySelected: 'TCEditorTheme__tableCellPrimarySelected',
    tableCellResizer: 'TCEditorTheme__tableCellResizer',
    tableCellSelected: 'TCEditorTheme__tableCellSelected',
    tableCellSortedIndicator: 'TCEditorTheme__tableCellSortedIndicator',
    tableResizeRuler: 'TCEditorTheme__tableCellResizeRuler',
    tableSelected: 'TCEditorTheme__tableSelected',
    tableSelection: 'TCEditorTheme__tableSelection',
    text: {
        bold: 'TCEditorTheme__textBold',
        code: 'TCEditorTheme__textCode',
        italic: 'TCEditorTheme__textItalic',
        strikethrough: 'TCEditorTheme__textStrikethrough',
        subscript: 'TCEditorTheme__textSubscript',
        superscript: 'TCEditorTheme__textSuperscript',
        underline: 'TCEditorTheme__textUnderline',
        underlineStrikethrough: 'TCEditorTheme__textUnderlineStrikethrough',
    },
};
